server:
  port: 6006

spring:
  application:
    name: mock-external-ms

mock:
  users:
    - subject: 00uothfqlvetIgGot5d7   # student1sso@mailinator.com
      roles:
        - ADMIN
        - USER
    - subject: 00uq55kmbsFTxD7n65d7   # student3sso@mailinator.com
      roles:
        - USER
