server:
  port: 6006

spring:
  application:
    name: mock-external-ms

mock:
  users:
    - subject: 00ux9q51j9gC67Mb5697   # mccsstest1@mailinator.com
      roles: [ADMIN, USER]
    - subject: 00ux9q60csGvJNV4x697   # student2sso@mailinator.com
      roles: [USER]
